config/routes.rb
Rails.application.routes.draw do
  resources :suggestions
  get 'static_pages/about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :replycomments
  resources :sarkarreplies
  resources :comments
  resources :problems

  root 'static_pages#about'

end

app/models/sarkarreply.rb
class Sarkarreply < ActiveRecord::Base
	belongs_to :problem
	has_many :replycomments
end

app/controllers/sarkarreplies_controller.rb
class SarkarrepliesController < ApplicationController
  before_action :set_sarkarreply, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin_user!, only: [:new] 

  # GET /sarkarreplies
  # GET /sarkarreplies.json
  def index
    @sarkarreplies = Sarkarreply.all
  end

  # GET /sarkarreplies/1
  # GET /sarkarreplies/1.json
  def show
  end

  # GET /sarkarreplies/new
  def new
    @sarkarreply = Sarkarreply.new
  end

  # GET /sarkarreplies/1/edit
  def edit
  end

  # POST /sarkarreplies
  # POST /sarkarreplies.json
  def create
    @sarkarreply = Sarkarreply.new(sarkarreply_params)

    respond_to do |format|
      if @sarkarreply.save
        format.html { redirect_to @sarkarreply, notice: 'Sarkarreply was successfully created.' }
        format.json { render :show, status: :created, location: @sarkarreply }
      else
        format.html { render :new }
        format.json { render json: @sarkarreply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sarkarreplies/1
  # PATCH/PUT /sarkarreplies/1.json
  def update
    respond_to do |format|
      if @sarkarreply.update(sarkarreply_params)
        format.html { redirect_to @sarkarreply, notice: 'Sarkarreply was successfully updated.' }
        format.json { render :show, status: :ok, location: @sarkarreply }
      else
        format.html { render :edit }
        format.json { render json: @sarkarreply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sarkarreplies/1
  # DELETE /sarkarreplies/1.json
  def destroy
    @sarkarreply.destroy
    respond_to do |format|
      format.html { redirect_to sarkarreplies_url, notice: 'Sarkarreply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sarkarreply
      @sarkarreply = Sarkarreply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sarkarreply_params
      params.require(:sarkarreply).permit(:reply)
    end
end

app/helpers/sarkarreplies_helper.rb
module SarkarrepliesHelper
end

app/views/sarkarreplies/_form.html.erb
<%= form_for(@sarkarreply) do |f| %>
  <% if @sarkarreply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sarkarreply.errors.count, "error") %> prohibited this sarkarreply from being saved:</h2>

      <ul>
      <% @sarkarreply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reply %><br>
    <%= f.text_field :reply %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sarkarreplies/edit.html.erb
<h1>Editing Sarkarreply</h1>

<%= render 'form' %>

<%= link_to 'Show', @sarkarreply %> |
<%= link_to 'Back', sarkarreplies_path %>

app/views/sarkarreplies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sarkarreplies</h1>

<table>
  <thead>
    <tr>
      <th>Reply</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sarkarreplies.each do |sarkarreply| %>
      <tr>
        <td><%= sarkarreply.reply %></td>
        <td><%= link_to 'Show', sarkarreply %></td>
        <td><%= link_to 'Edit', edit_sarkarreply_path(sarkarreply) %></td>
        <td><%= link_to 'Destroy', sarkarreply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sarkarreply', new_sarkarreply_path %>
<%= link_to 'Back', problems_path %>

app/views/sarkarreplies/new.html.erb
<h1>New Sarkarreply</h1>

<%= render 'form' %>

<%= link_to 'Back', sarkarreplies_path %>

app/views/sarkarreplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reply:</strong>
  <%= @sarkarreply.reply %>
</p>

<%= link_to 'Edit', edit_sarkarreply_path(@sarkarreply) %> |
<%= link_to 'Back', sarkarreplies_path %>