config/routes.rb
Rails.application.routes.draw do
  resources :suggestions
  get 'static_pages/about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :replycomments
  resources :sarkarreplies
  resources :comments
  resources :problems

  root 'static_pages#about'

end

app/models/replycomment.rb
class Replycomment < ActiveRecord::Base
	belongs_to :sarkarreply
end

app/controllers/replycomments_controller.rb
class ReplycommentsController < ApplicationController
  before_action :set_replycomment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /replycomments
  # GET /replycomments.json
  def index
    @replycomments = Replycomment.all
  end

  # GET /replycomments/1
  # GET /replycomments/1.json
  def show
  end

  # GET /replycomments/new
  def new
    @replycomment = Replycomment.new
  end

  # GET /replycomments/1/edit
  def edit
  end

  # POST /replycomments
  # POST /replycomments.json
  def create
    @replycomment = Replycomment.new(replycomment_params)

    respond_to do |format|
      if @replycomment.save
        format.html { redirect_to @replycomment, notice: 'Replycomment was successfully created.' }
        format.json { render :show, status: :created, location: @replycomment }
      else
        format.html { render :new }
        format.json { render json: @replycomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replycomments/1
  # PATCH/PUT /replycomments/1.json
  def update
    respond_to do |format|
      if @replycomment.update(replycomment_params)
        format.html { redirect_to @replycomment, notice: 'Replycomment was successfully updated.' }
        format.json { render :show, status: :ok, location: @replycomment }
      else
        format.html { render :edit }
        format.json { render json: @replycomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replycomments/1
  # DELETE /replycomments/1.json
  def destroy
    @replycomment.destroy
    respond_to do |format|
      format.html { redirect_to replycomments_url, notice: 'Replycomment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_replycomment
      @replycomment = Replycomment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def replycomment_params
      params.require(:replycomment).permit(:comment)
    end
end

app/helpers/replycomments_helper.rb
module ReplycommentsHelper
end

app/views/replycomments/_form.html.erb
<%= form_for(@replycomment) do |f| %>
  <% if @replycomment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@replycomment.errors.count, "error") %> prohibited this replycomment from being saved:</h2>

      <ul>
      <% @replycomment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replycomments/edit.html.erb
<h1>Editing Replycomment</h1>

<%= render 'form' %>

<%= link_to 'Show', @replycomment %> |
<%= link_to 'Back', replycomments_path %>

app/views/replycomments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Replycomments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replycomments.each do |replycomment| %>
      <tr>
        <td><%= replycomment.comment %></td>
        <td><%= link_to 'Show', replycomment %></td>
        <td><%= link_to 'Edit', edit_replycomment_path(replycomment) %></td>
        <td><%= link_to 'Destroy', replycomment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Replycomment', new_replycomment_path %>

app/views/replycomments/new.html.erb
<h1>New Replycomment</h1>

<%= render 'form' %>

<%= link_to 'Back', replycomments_path %>

app/views/replycomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @replycomment.comment %>
</p>

<%= link_to 'Edit', edit_replycomment_path(@replycomment) %> |
<%= link_to 'Back', replycomments_path %>